### ISSUE TITLE
Implement Clone + Copy on your types

### ISSUE THREAD

**Issue by djflex68** [minghuaw/fe2o3-amqp#125]
It would be nice if the several types used in this crate all implement Clone and Copy.
For some reason, I need to call send method of the Sender inside an async loop. I need to use "move" but none of those types implement Clone and Copy, making it impossible to use.
At least : 
- ConnectionHandle
-  Sender
- SessionHandle

Thanks

**Comment by minghuaw** [comment]
For the three types you mentioned, I intentionally didn't implement `Clone` or `Copy` trait, which I will explain below.

1. `ConnectionHandle`/`SessionHandle` - it internally holds a `tokio::task::JoinHandle` (https://docs.rs/tokio/1.21.2/tokio/task/struct.JoinHandle.html) to the connection/session event loop task, and the `JoinHandle` doesn't implement `Clone` or `Copy`. It also doesn't make sense to have multiple `JoinHandle` to one task.
2. `Sender` - it internally holds a `tokio::sync::mpsc::Receiver`, which as the name mpsc (multiple producer single consumer) suggests, doesn't allow multiple `Receiver` to the same channel, and thus `Receiver` doesn't implement `Clone` either.

Is your async loop running as a separate task? I remember there was some "trick" needed to pass ownership of a `Sender` when spawning an async task a while ago. Could you please show me some code snippet showcasing the usage?

Another common option is to wrap the type in an `Arc` or `Arc<Mutex>`

**Comment by djflex68** [comment]
Sorry I didn't had the time to answer, there were a couple of days off here in France.
Yes i understand the reasons why you did not implement the copy trait, but since I'm new in Rust, I didn't find the right way to move some variables that don't implement Copy inside an async closure.
Maybe you could give me some hints here ? Arc<Mutext> could be one way to go. Here is my code :

```
pub async fn start_publishing(mut self, micro_service_name: &str) {
        // self.amqpConnection = Some(connection);
        let mut connection =
        Connection::open(micro_service_name, "amqp://guest:guest@localhost:5672")
            .await
            .unwrap();

        let mut session = Session::begin(&mut connection).await.unwrap();

        // Create a sender
        let sender = Sender::attach(
            &mut session,                                   // Session
            format!("{}-{}", micro_service_name, "sender"), // link name
            micro_service_name,                             // target address
        )
        .await
        .unwrap();

        self.sender = Some(sender);
        // let this = RefCell::new(self);

        let interval = time::interval(Duration::from_millis(500));
        let forever = stream::unfold(interval, |mut interval| async move {
            interval.tick().await;
            self.poll_and_publish_events().await; // Error occurs here because self contains a reference to Sender
            Some(((), interval)) 
        });

        forever.for_each(|_| async {}).await;
    }
```

And the structure Event Relay looks like : 

```
pub struct EventRelay {
    db: &'static Db,
    // amqpConnection: ConnectionHandle<()>, // TODO : amqpclient
    sender: Option<Sender>,
    // micro_service_name: String,
}
```

The method   `async fn poll_and_publish_events(self)` cannot be called because self cannot be moved inside the async closure. I didn't find a proper way to get rid of this error...

**Comment by minghuaw** [comment]
Could you please show me what `fn poll_and_publish_events()` looks like? The function signature should be enough. 

My initial guess (very likely wrong) is that `self` might be consumed when calling `poll_and_publish_events`, and `stream::unfold` is kind of like a for loop, if something is consumed in the first iteration and is not `Clone` or `Copy`, then in the second iteration, you are calling a function on something that is already consumed, and thus the compiler complains

**Comment by djflex68** [comment]
Here is my function (thanks for the support on something not directly related to your library 😄 )

```
    async fn poll_and_publish_events(self) {
        let events = transaction_outbox
            .load::<TransactionOutbox>(self.db.connection())
            .unwrap();

            let mut sender = self.sender.unwrap();
            let mut iter = stream::iter(events);

            while let Some(item) = iter.next().await {
                let outcome: Outcome = sender.send(item.event_data).await.unwrap();
                outcome.accepted_or_else(|state| state).unwrap(); // Handle delivery outcome

                diesel::update(transaction_outbox
                    .filter(id.eq(item.id).and(published.eq(false))))
                    .set(id.eq(0))
                    .execute(self.db.connection());
            }
    }
```

The error got from the compiler is : 

```
event_relay.rs(40, 35): captured outer variable
event_relay.rs(64, 48): captured by this `FnMut` closure
event_relay.rs(67, 13): variable moved due to use in generator
event_relay.rs(67, 13): move occurs because `self` has type `EventRelay`, which does not implement the `Copy` trait
```

**Comment by minghuaw** [comment]
Here is a minimal working example (tested on my machine). I used a u32 iterator to mimic your DB events, and instead of using `futures::stream::unfold`, `tokio::time::Interval` can be turned into a `Stream` with `tokio-stream::wrappers::IntervalStream` as described in tokio's documentation (https://docs.rs/tokio/1.21.2/tokio/time/struct.Interval.html).

```toml
[dependencies]
tokio = { version = "1", features = ["net", "rt", "rt-multi-thread", "macros"] }
fe2o3-amqp = "0.7.4"
tokio-stream = "0.1"
```

```rust
use std::time::Duration;

use fe2o3_amqp::{connection::Connection, session::Session, Sender};
use tokio::time;
use tokio_stream::{wrappers::IntervalStream, StreamExt};

pub struct EventRelay {
    db: u32, // increment this to simulate a streaming message source
    sender: Option<Sender>,
}

impl EventRelay {
    async fn poll_and_publish_events(&mut self) {
        let iter = self.db..u32::MAX; // This creates an iterator from self.db to u32::MAX

        if let Some(sender) = &mut self.sender {
            for event in iter {
                let outcome = sender.send(event).await.unwrap();
                outcome.accepted_or("not accepted").unwrap();
            }
        }
    }

    async fn start_publishing(mut self) {
        let mut connection = Connection::open("connection-1", "amqp://localhost:5672")
            .await
            .unwrap();
        let mut session = Session::begin(&mut connection).await.unwrap();
        let sender = Sender::attach(&mut session, "rust-sender-link-1", "q1")
            .await
            .unwrap();
        self.sender = Some(sender);

        let interval = time::interval(Duration::from_millis(500));
        let mut interval_stream = IntervalStream::new(interval);

        while let Some(_) = interval_stream.next().await {
            self.poll_and_publish_events().await;
        }

        if let Some(sender) = self.sender {
            sender.close().await.unwrap();
        }
        session.end().await.unwrap();
        connection.close().await.unwrap();
    }
}

#[tokio::main]
async fn main() {
    let event_relay = EventRelay { db: 0, sender: None };
    event_relay.start_publishing().await;
}

```

**Comment by minghuaw** [comment]
And forgot to point out another change. `poll_and_publish_events` now takes a mutable reference of `self` instead of taking the ownership of `self`

**Comment by djflex68** [comment]
I'm gonna giving it a try right now. I didn't know that "for...in loop" would work well with some async code inside ? Does this sequentially run async code (as a "for ... await" would do in other languages ?)

**Comment by djflex68** [comment]
It seems that your code works better that mine 😄 
In fact we mainly solved the problem by removing the closure, didn't we ? Still not clear for me what one have to do in case of a "non-copiable" variable passed inside a closure and you can't implement the Copy trait, hopefully I'm never getting this case anymore ^^

Now I'm just getting some error on sender.send(event), that I'm trying to get rid off, shouldn't be that difficult

```
the trait bound `TransactionOutbox: IntoBody` is not satisfied
the following other types implement trait `IntoBody`:
  &'a T
  &'a str
  ()
  AmqpSequence<T>
  AmqpValue<T>
  BTreeMap<K, V>
  Cow<'a, str>
  Dec128
and 29 others
required because of the requirements on the impl of `IntoBody` for `&TransactionOutbox`
required because of the requirements on the impl of `From<&TransactionOutbox>` for `fe2o3_amqp::types::messaging::Message<_>`
required because of the requirements on the impl of `Into<fe2o3_amqp::types::messaging::Message<_>>` for `&TransactionOutbox`
2 redundant requirements hidden
required because of the requirements on the impl of `Into<Sendable<_>>` for `&TransactionOutbox`rustc[E0277](https://doc.rust-lang.org/error-index.html#E0277)
```

**Comment by minghuaw** [comment]
I think closure can cause weird lifetine issues until async closure is stablized. I will close the issue for now then

**Comment by minghuaw** [comment]
> Many thanks for you code sample, I'm gonna giving it a try right now. I didn't know that "for...in loop" would work well with some async code inside ? Does this sequentially run async code (as a "for ... await" would do in other languages ?)
> 
> Note : after looking at the tokio_stream documentation [here](https://tokio.rs/tokio/tutorial/streams) it states that : 
> 
> > Currently, the Rust programming language does not support async for loops. Instead, iterating streams is done using a while let loop paired with [StreamExt::next()](https://docs.rs/tokio-stream/0.1/tokio_stream/trait.StreamExt.html#method.next).
> 
> with that example 
> 
> ```
> use tokio_stream::StreamExt;
> 
> #[tokio::main]
> async fn main() {
>     let mut stream = tokio_stream::iter(&[1, 2, 3]);
> 
>     while let Some(v) = stream.next().await {
>         println!("GOT = {:?}", v);
>     }
> }
> ```
> 
> So may I propose to rewrite the poll_and_publish_events method as : 
> ```
>     async fn poll_and_publish_events(&mut self) {
>         let events = transaction_outbox
>             .load::<TransactionOutbox>(self.db.connection())
>             .unwrap();
> 
>             let mut stream = tokio_stream::iter(events);
> 
>             if let Some(sender) = &mut self.sender {
>                 while let Some(event) =  stream.next().await {
>                     let outcome = sender.send(&event).await.unwrap();
>                     outcome.accepted_or("not accepted").unwrap();
>                 }
>             }
> }
> ```
> 

This fits your needs. My example is a simple iterator that is not async so a for loop was fine, and it was only demonstrating the idea
