### ISSUE TITLE
Equivalency to JSM selector

### ISSUE THREAD

**Issue by VLorz** [minghuaw/fe2o3-amqp#202]
I need to receive messages from a broker on a topic using a selector. Available sample code is in Java and uses a JMS Message Selector, using an annotation similar to this:
````java
    @JmsListener(destination = "my.topic", containerFactory = "myFactory", selector = 
        "((DEVICECLASS IS NULL) AND (DEVICEID=123456)) OR " +
        "((DEVICEID=123456) AND (DEVICECLASS='SOMETHING')) OR " +
        "((DEVICEID IS NULL) AND (DEVICECLASS IS NULL)) OR " +
        "((DEVICEID IS NULL) AND (DEVICECLASS='SOMETHING'))"
    )
````

`DEVICECLASS` and `DEVICEID` are message properties set by the message sender.
The sample code [receive with filter](https://github.com/minghuaw/fe2o3-amqp/blob/main/examples/recv_with_filter/src/main.rs) sets a selector filter, but uses a `key` which is a bit confusing for me, as it has same property name as used in the filter.

````rust
    let source = Source::builder()
        .address("q1")
        .add_to_filter("sn", SelectorFilter(String::from("sn = 100")))
        .build();
````

What is the equivalent form in **fe2o3** library for specifying the selector filter like in previous JMS example?
Thanks a lot in advance.

**Comment by minghuaw** [comment]
Hi @VLorz 

The key shouldn't matter. You should be able to use any string value for your key. I was just being lazy when I coded that example. More details on translating JMS selector filter to AMQP 1.0 selector filter can be found on this doc (https://svn.apache.org/repos/asf/qpid/trunk/qpid/specs/apache-filters.xml#type-selector-filter).

Feel free to let me know if this helps :)

**Comment by VLorz** [comment]
Hi @minghuaw, it worked against an ActiveMQ 5.16.3 using "selector" as key.
I think it was not working previously due to an invalid character I seem to have introduced in the selector query.
Thanks a lot once again!
