### ISSUE TITLE
Cancellation safety 

### ISSUE THREAD

**Issue by minghuaw** [minghuaw/fe2o3-amqp#22]
Some `tokio` primitives are not cancellation safe and may lead to loss of data in `tokio::select!`. `Notify` is one of them. Whether cancellation safety should be taken care of should be investigated.

> The following methods are cancellation safe:
>
>    [tokio::sync::mpsc::Receiver::recv](https://docs.rs/tokio/1.21.1/tokio/sync/mpsc/struct.Receiver.html#method.recv)
    [tokio::sync::mpsc::UnboundedReceiver::recv](https://docs.rs/tokio/1.21.1/tokio/sync/mpsc/struct.UnboundedReceiver.html#method.recv)
    [tokio::sync::broadcast::Receiver::recv](https://docs.rs/tokio/1.21.1/tokio/sync/broadcast/struct.Receiver.html#method.recv)
    [tokio::sync::watch::Receiver::changed](https://docs.rs/tokio/1.21.1/tokio/sync/watch/struct.Receiver.html#method.changed)
    [tokio::net::TcpListener::accept](https://docs.rs/tokio/1.21.1/tokio/net/struct.TcpListener.html#method.accept)
    [tokio::net::UnixListener::accept](https://docs.rs/tokio/1.21.1/tokio/net/struct.UnixListener.html#method.accept)
    [tokio::signal::unix::Signal::recv](https://docs.rs/tokio/1.21.1/tokio/signal/unix/struct.Signal.html#method.recv)
    [tokio::io::AsyncReadExt::read](https://docs.rs/tokio/1.21.1/tokio/io/trait.AsyncReadExt.html#method.read) on any AsyncRead
    [tokio::io::AsyncReadExt::read_buf](https://docs.rs/tokio/1.21.1/tokio/io/trait.AsyncReadExt.html#method.read_buf) on any AsyncRead
    [tokio::io::AsyncWriteExt::write](https://docs.rs/tokio/1.21.1/tokio/io/trait.AsyncWriteExt.html#method.write) on any AsyncWrite
    [tokio::io::AsyncWriteExt::write_buf](https://docs.rs/tokio/1.21.1/tokio/io/trait.AsyncWriteExt.html#method.write_buf) on any AsyncWrite
    [tokio_stream::StreamExt::next](https://docs.rs/tokio-stream/0.1/tokio_stream/trait.StreamExt.html#method.next) on any Stream
    [futures::stream::StreamExt::next](https://docs.rs/futures/0.3/futures/stream/trait.StreamExt.html#method.next) on any Stream
>
> The following methods are not cancellation safe and can lead to loss of data:
>
>    [tokio::io::AsyncReadExt::read_exact](https://docs.rs/tokio/1.21.1/tokio/io/trait.AsyncReadExt.html#method.read_exact)
    [tokio::io::AsyncReadExt::read_to_end](https://docs.rs/tokio/1.21.1/tokio/io/trait.AsyncReadExt.html#method.read_to_end)
    [tokio::io::AsyncReadExt::read_to_string](https://docs.rs/tokio/1.21.1/tokio/io/trait.AsyncReadExt.html#method.read_to_string)
    [tokio::io::AsyncWriteExt::write_all](https://docs.rs/tokio/1.21.1/tokio/io/trait.AsyncWriteExt.html#method.write_all)
>
> The following methods are not cancellation safe because they use a queue for fairness and cancellation makes you lose your place in the queue:
> 
>    [tokio::sync::Mutex::lock](https://docs.rs/tokio/1.21.1/tokio/sync/struct.Mutex.html#method.lock)
    [tokio::sync::RwLock::read](https://docs.rs/tokio/1.21.1/tokio/sync/struct.RwLock.html#method.read)
    [tokio::sync::RwLock::write](https://docs.rs/tokio/1.21.1/tokio/sync/struct.RwLock.html#method.write)
    [tokio::sync::Semaphore::acquire](https://docs.rs/tokio/1.21.1/tokio/sync/struct.Semaphore.html#method.acquire)
    [tokio::sync::Notify::notified](https://docs.rs/tokio/1.21.1/tokio/sync/struct.Notify.html#method.notified)

**Comment by roblperry** [comment]
I wonder if this relates to an issue I am having. I was trying to offload the processing of deliveries to other tasks and then accept the messages after processing them has been completed.  However, both reciever.recv and receiever.accept require a mutable receiver.  I attempted to work around this by protecting the receiver with a Mutex, and using select! to cause the lock to be released.

The resulting code looks like this:
```
let receiver_lock = Arc::new(Mutex::new(receiver));
            loop {
                select! {
                    delivery = async { receiver_lock.lock().await.recv::<String>().await } => {
                        process_delivery(delivery.unwrap(), receiver_lock.clone(), tx.clone(), processor.clone());
                    }

                    Some(cmd) = rx.recv() => {
                        process_command(cmd).await;
                    }
                }
            }
```

Where process_delivery sends a message via rx.recv() in order to obtain the receiver from the Mutex.

The result is a loss of 4-20 deliveries in 100,000, when I am bombarding the receiver with messages. However, since the lost deliveries are not accepted, the messages are still retained by the broker.  I am not certain that I am working in an appropriate direction, but it would seem to me that an issue does exist around safely Cancelling a receiver.recv, and I thought it might be relevant to the questions of if cancellation safety should be taken care of.

**Comment by minghuaw** [comment]
Thanks! That does look like a problem with cancellation safety. I think there are potentially two things that I can (and most likely will) do

1. Replacing the internal state that are mutated during `receiver.accept()` with their atomic counterpart and thus making `accept()` not requiring a mutable reference. (However, this wouldn't get rid of the `&mut self` requirement on `receiver.recv()`) 
2. Making `receiver.recv()` cancellation safe. This is probably going to take me some time though, as it would require checking every `.await` point during the function call.

In the meanwhile, I am going to try to find a temporary solution hopefully today.

**Comment by roblperry** [comment]
Removing the need for a mutable reference for the accept sounds like a win.  I could use a RwLock instead of a Mutex and have less contention between tasks wanting to accept. I a minor win perhaps, but still a win.

I have a ways to go before I need what I am working on to be rock solid and most of my time is going to learning how to think in Rust.  To that end, I am most eager to see how you address the second item.  I expect I'll learn a thing or two reading through your changes.  In the meantime I continue to enjoy and appreciate fe2o3-amqp.

**Comment by minghuaw** [comment]
I cannot really find a guaranteed workaround (after trying for like three hours) without fixing those two things mentioned above. I will start working on those two and try to make a working example later today or tomorrow.

**Comment by minghuaw** [comment]
## Problem diagnosis

Reviewing/fixing cancel safety on `Receiver::recv()` was actually easier than expected. The futures that were not cancel safe were all related to `tokio::sync::RwLock`. 

## Solution

So all `tokio::sync::RwLock` have been replaced with `parking_lot::RwLock`, which is a blocking `RwLock`. However, `RwLock` usage is Okay here because the lock guard is not held across any `.await` point or any IO operations, and according to `tokio`'s documentation

> Contrary to popular belief, it is ok and often preferred to use the ordinary [Mutex](https://doc.rust-lang.org/nightly/std/sync/mutex/struct.Mutex.html) from the standard library in asynchronous code.
>
> The feature that the async mutex offers over the blocking mutex is the ability to keep it locked across an .await point. This makes the async mutex more expensive than the blocking mutex, so the blocking mutex should be preferred in the cases where it can be used. The primary use case for the async mutex is to provide shared mutable access to IO resources such as a database connection. If the value behind the mutex is just data, it’s usually appropriate to use a blocking mutex such as the one in the standard library or [parking_lot](https://docs.rs/parking_lot).

## Test

An example was created (https://github.com/minghuaw/fe2o3-amqp/tree/main/examples/cancel_safety) to test cancel safety by receiving a large number of messages (`1_000_000` messages), spawning a separate task to process the message, and then the receiver accepts the message after it is processed. The test example seems to work fine with repeated testing.

## Release

This fix can be found as part of `"v0.6.7"` release.

**Comment by minghuaw** [comment]
- [ ] It is probably a good idea to review/fix cancel safety issue for `Sender::send` and `Sender::send_batchable()`

**Comment by roblperry** [comment]
Awesome!!!  The new cancel_safety example looks like a good test.  I look forward to seeing what I can learn by reviewing the rest of the changes and retesting my code with the new version.  Sadly, I can't get to that until this evening. (US Eastern Time)

Thank you again for fe2o3-amqp and all the work you generously pour into it.

**Comment by roblperry** [comment]
Seems rock solid to me.  My code that was previously dropping between 4-20 deliveries in 100,000 has not processed 500,000 without a single drop.

**Comment by minghuaw** [comment]
> * [x]  It is probably a good idea to review/fix cancel safety issue for `Sender::send` and `Sender::send_batchable()` (`Notify` is used on the sender side, and it is not cancel safe)

# Reviewing cancel safety on `Sender::send`

version: 0.6.7

## Cancel safety at `.await` points

The internal `.await` points during `Sender::send` fall into the following categories

1. `tokio::mpsc::Sender::send(item)`. 
    This is cancel safe, and cancelled future guarantee that the item is not sent.
2. `tokio::sync::Notify::notified()`
    This is **NOT** cancel safe. The `Notified` future will lose its place in the queue upon cancelling. However, because the `Notify` pair are put into a single producer single consumer pattern, losing place in the queue simply means re-queuing back to the same place, thus making the usage cancel safe.

## Testing cancel safety

I haven't found a neat way to test cancellation safety on the Sender itself. However, a few unit tests have been written to test the `Producer` and `Consumer` that internally uses `tokio::sync::Notify`, which is the only `.await` point that is not cancel safe. 

1. https://github.com/minghuaw/fe2o3-amqp/blob/744137db0ae067c664f16c429d7022e430ee1161/fe2o3-amqp/src/link/state.rs#L449
2. https://github.com/minghuaw/fe2o3-amqp/blob/744137db0ae067c664f16c429d7022e430ee1161/fe2o3-amqp/src/link/state.rs#L475

The testing shows that the future returned by `Consumer::consume(1)` is cancel safe. More specifically, the test shows that dropping `Consumer::consume(1)` future either before or after producing will not mistakenly consume the credit.
