### ISSUE TITLE
Receive Message without apriori knowledge of the message body type

### ISSUE THREAD

**Issue by LarryOsterman** [minghuaw/fe2o3-amqp#235]
Looking at the Message and Receiver structs, it appears that it is not possible to receive a message without the caller having apriori knowledge of the underlying message format.

The challenge here is that a message receiver has no way of knowing what type of message was sent from the sender, so an API surface which forces the receiver to know the type of message being received is going to be challenging.

Knowing the body type of message on Send is reasonable because the sender always knows what they're sending, but for a receiver it is challenging.

For reference, other AMQP implementation handle this differently - they typically define a Message type with 3 fields, one for each possible body type, and then fill in the appropriate fields (either one or zero of the fields).

Here's the definition of Message for [Go AMQP](https://github.com/Azure/go-amqp/blob/1003610b1e679a884a60f9011c37e55c6eb07338/message.go#L88)

Here's the definition of Message for [Python AMQP](https://github.com/Azure/azure-sdk-for-python/blob/9d08ae8a46b32eb2417636f434fc2e38eb97f9ec/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/message.py#L26) and where [it's decoded](https://github.com/Azure/azure-sdk-for-python/blob/9d08ae8a46b32eb2417636f434fc2e38eb97f9ec/sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_decode.py#L246)

Here's the definition of Message for [Java AMQP](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/MessageUtils.java#L68) - note that Java doesn't yet support Sequence or Value.

Here's the definition of Message for [uAMQP](https://github.com/Azure/azure-uamqp-c/blob/9c8c1805fac797e2d14a32ff6a7d9756a5ee82e1/src/message.c#L23-L27).

What is common among all of these is that the receiver (or creator) Message object doesn't know the underlying body type.

Would it be possible to enable receiving messages where the receiver doesn't know the type of message being received ahead of time?

Please note that I am *not* an expert Rust developer. If it is already possible to receive messages without knowing the incoming message type, I would *love* to be wrong.

**Comment by minghuaw** [comment]
I think this is already covered by using `Body<Value>` as the receiving type. It is kind of hard to find this in the documentation, which is my fault.

https://docs.rs/fe2o3-amqp/latest/fe2o3_amqp/link/receiver/struct.Receiver.html#method.recv

> If the user is not certain the exact type (including the exact body section type) to receive, [Body<Value>](https://docs.rs/fe2o3-amqp/latest/fe2o3_amqp/types/messaging/enum.Body.html) is probably the safest bet. [Body<T>](https://docs.rs/fe2o3-amqp/latest/fe2o3_amqp/types/messaging/enum.Body.html) covers all possible body section types, including an empty body, and Value covers all possible AMQP 1.0 types

The `Body<T>`type covers all possible body section defined in the spec (http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#section-message-format) including an empty body, which was an unintended mistake in the spec (https://issues.apache.org/jira/browse/PROTON-2574?filter=-2). 

The documentation of `Body<T>` can be found here: https://docs.rs/fe2o3-amqp/latest/fe2o3_amqp/types/messaging/enum.Body.html

**Comment by minghuaw** [comment]
Here is a simple example showing receiving a message from Service Bus without knowing the type beforehand and then try to interpret the message as a `Data` section that contains a string. The unwrapping and next are there because the `Body`  could have one or more `Data` sections, and the example is only inspecting the first one.

https://github.com/minghuaw/fe2o3-amqp/blob/ddc8f3bf654ebbff5bed8133ce839f60c7ba20c9/examples/service_bus/src/bin/topic_receiver.rs#L39-L40

The `Body` type allows the user to inspect the body section type. If the body section is an [`AmqpValue`](https://docs.rs/fe2o3-amqp/latest/fe2o3_amqp/types/messaging/struct.AmqpValue.html), the user could then deserialize that `Value` using the method [from_value](https://docs.rs/serde_amqp/latest/serde_amqp/fn.from_value.html)

**Comment by LarryOsterman** [comment]
Ah, thank you, that answers my question. I had noticed the `Body<Value>` variant and was trying to use it, but I missed the `try_as_data()`/`try_as_value()`/`try_as_sequence()` functions on the `Body<T>` type.
