### ISSUE TITLE
Does this library rely on Tokio runtime or just Tokio utilities? 

### ISSUE THREAD

**Issue by lsunsi** [minghuaw/fe2o3-amqp#240]
More specifically and I think this question can be useful for more people: would this crate work with async-std or smol? I case it wouldn't, what are the main hang ups for it to be runtime agnostic?

Personally I use Tokio but it seems like a library like this one would not need to make this choice!

**Comment by minghuaw** [comment]
It's actually mentioned here #89. It definitely could be more runtime agnostic, but `tokio` was chosen mainly because of the ecosystem and there's not really a feature request for supporting other runtime yet.

**Comment by lsunsi** [comment]
@minghuaw Makes sense! I'll read more about it, it's refreshing to see how organized you are with issues and information about the project. Thanks again (:
